# Generated by Django 5.0.3 on 2024-03-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='password1',
            new_name='password',
        ),
    ]
