# Generated by Django 5.0.3 on 2024-03-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
