# Generated by Django 5.0.3 on 2024-03-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_rename_password1_userrole_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='password',
            new_name='password1',
        ),
    ]
