# Generated by Django 5.0.3 on 2024-03-22 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('personal', '0003_rename_password_userrole_password1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
